/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
    return {
        GameData: (() => {
            return defineComponent(
                world,
                {
                    game: RecsType.BigInt,
                    number_of_players: RecsType.BigInt,
                    available_ids: RecsType.BigInt,
                },
                {
                    metadata: {
                        name: "GameData",
                        types: ["felt252", "u128", "u128"],
                        customTypes: [],
                    },
                }
            );
        })(),
        PlayerAddress: (() => {
            return defineComponent(
                world,
                { player_id: RecsType.BigInt, player_address: RecsType.BigInt },
                {
                    metadata: {
                        name: "PlayerAddress",
                        types: ["u128", "contractaddress"],
                        customTypes: [],
                    },
                }
            );
        })(),
        PlayerId: (() => {
            return defineComponent(
                world,
                { player_address: RecsType.BigInt, player_id: RecsType.BigInt },
                {
                    metadata: {
                        name: "PlayerId",
                        types: ["contractaddress", "u128"],
                        customTypes: [],
                    },
                }
            );
        })(),
        RemainingMoves: (() => {
            return defineComponent(
                world,
                { player_id: RecsType.BigInt, moves: RecsType.Number },
                {
                    metadata: {
                        name: "RemainingMoves",
                        types: ["u128", "u8"],
                        customTypes: [],
                    },
                }
            );
        })(),
        Score: (() => {
            return defineComponent(
                world,
                { player_id: RecsType.BigInt, score: RecsType.Number },
                {
                    metadata: {
                        name: "Score",
                        types: ["u128", "u8"],
                        customTypes: [],
                    },
                }
            );
        })(),
        Tile: (() => {
            return defineComponent(
                world,
                {
                    row: RecsType.Number,
                    col: RecsType.Number,
                    player_id: RecsType.BigInt,
                    tile_type: RecsType.Number,
                    counted: RecsType.Boolean,
                    is_hill: RecsType.Boolean,
                },
                {
                    metadata: {
                        name: "Tile",
                        types: ["u8", "u8", "u128", "enum", "bool", "bool"],
                        customTypes: ["TileType"],
                    },
                }
            );
        })(),
    };
}
